### ISSUE TITLE
Don't publish .ts files to npm

### ISSUE THREAD

**Issue by chancancode** [stefanpenner/fs-tree-diff#93]
I'm getting this error when trying to run `tsc` against an Ember project.

```
node_modules/broccoli-funnel/node_modules/fs-tree-diff/lib/entry.ts:3:1 - error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

3 import fs = require('fs');
  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I believe the problem is that version 2.0.1 was published with both `.js`, `.ts` and `.d.ts` files to npm. Since `index.d.ts` imports from `./entry` and there is an `entry.ts` next to `entry.d.ts`, the former takes precedence. And since it is a `.ts` file, `tsc` uses different rules for checking. For example, `skipLibCheck` only applies to declaration files, and `entry.d.ts` has extra encodings in it based on its `tsconfig.json` that didn't get picked up this way.

Deleting the `*.ts` files from the `fs-tree-diff` folder in `node_modules` fixed the problem.

**Comment by dfreeman** [comment]
In general, not publishing `.ts` files to npm is a good call, since (as you've seen here) they take precedence over `.d.ts` files. Aside from being immune to certain classes of errors like this one, `.d.ts` files are also typically more performant for typechecking in consuming projects, since they just exist as a vehicle for type annotations and therefore don't require any checking or inference themselves.

In this case, though, the underlying issue seems to be the prevailing use of `import ... = require()`, which `tsc` allows within this project because [its module target is `'commonjs'`](https://github.com/stefanpenner/fs-tree-diff/blob/master/tsconfig.json#L6), but will cause trouble for consumers with other config when used to import from ES modules (which is how the node types are declared, leading to `import fs = require('fs')` being flagged in your error message).

I think the general recommendation these days is to avoid `import ... = require()` entirely in favor of setting `esModuleInterop: true` in `tsconfig.json`. This allows you to use ES imports regardless of how the source module was declared, with a synthesized default export for CJS modules that gives you the equivalent of `require`-ing it.

**Comment by chancancode** [comment]
If we are going to make code changes, then `esModuleInterop` or not is kind of moot, because we can just use named imports instead of importing `fs` itself.

**Comment by chancancode** [comment]
Ah, but there are more imports from `index`

**Comment by stefanpenner** [comment]
> Don't publish .ts files to npm

@chancancode  unfortunately that appears to negatively affect sourcemap affectiveness..
